development: 
  database: demo_julio
  adapter: mysql2
  host: localhost
  username:  root
  password:
  pool: 5
  timeout: 5000

test: 
  database: demo_julio_test
  adapter: mysql2
  host: localhost
  username:  root
  password:
  pool: 5
  timeout: 5000